version: 2.1

jobs:
  build:
    docker:
      - image: macandkaj/stm32f0_development
        auth:
          username: macandkaj
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run:
          name: build-app
          command: ./bootstrapper.sh build;
      - store_artifacts:
          path: /root/project/build/MotorDriverCard.hex
      - store_artifacts:
          path: /root/project/build/MotorDriverCard.bin
      - store_artifacts:
          path: /root/project/build/MotorDriverCard.elf


workflows:
  MDC-workflow:
    jobs:
      - build